
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FuelRecords' AND COLUMN_NAME = 'ExternalID')
BEGIN
    ALTER TABLE FuelRecords ADD ExternalID NVARCHAR(100) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FuelRecords' AND COLUMN_NAME = 'Source')
BEGIN
    ALTER TABLE FuelRecords ADD Source NVARCHAR(50) DEFAULT 'Manual' WITH VALUES;
END
